### PR TITLE
event page

### LINKED ISSUE #15: Events view
- Show events:
  - endpoint: GET /api/events
  - response: {"allEvents", [EventEntity]}
  
```kotlin
data class EventEntity(
        var title: String = "",
        var category: String = "", // (optional) TALK, QUIZ, GAME, GENERIC, ...
        var timestampStart: Long = 0,
        var timestampEnd: Long = 0,
        var place: String = "",
        var previewDescription: String = "",
        var previewImageUrl: String = "",
}
```

### PR DESCRIPTION
**Pull request by DannySS123**
Since we don't know how the events will look like, I made a page for them just in case.
Closes #15

### CODE REVIEW

**Comment by berenteb** [comment]
We will talk about this later, good to have it! Nice!

**Review by berenteb — CHANGES_REQUESTED** [review]
Looks clean, nice job! We will talk about the future of this feature soon. IMO this feature has a bright future in this project! One minor thing I saw was an individual component defined inside another component, jsut move it outside and use props you already defined for it!

**Review by triszt4n — APPROVED** [review]
Good job Dani 🧇 🥇

**Review by berenteb — APPROVED** [review]
Lessgooo

**Pull request merged**
