### PR TITLE
Added ServiceContex

### PR DESCRIPTION
**Pull request by berenteb**
This is a concept of a context that can be used to display error messages. It has a throwError function, which sets an error state, redirects to an error page, displays the error and then clears the error.

There are several options for this function, i.e. an option to display only a toast instead of the ErrorPage.

The error page normally redirects to the home page if no error is present in the context.

It seems to be working fine, and easy to use. Please try it and I am waiting for suggestions whether this is acceptable.

I tried to implement a unified axios call, but found no need for it, since every API call needs its own error handling, and the code for it was very ugly (generic types, typecheck, code duplication etc.)

### CODE REVIEW

**Comment by triszt4n** [comment]
As we discussed, maybe use io-ts or sth for response type validation/verification

**Comment by berenteb** [comment]
> As we discussed, maybe use io-ts or sth for response type validation/verification

We discussed the absolute opposite: the API will not send back invalid data if the response code is OK.

**Review by triszt4n — APPROVED** [review]
I don't see anything preventing this PR from merging, these context functions shall be used by other devs ⛵

**Review by poiuztrewq1 — APPROVED** [review]
👍

**Pull request merged**
