### PR TITLE
Impressum page

### LINKED ISSUE #121: Create an Impressum page
- Add a link to the footer called 'Impresszum'
- Impresszum page:
  - Header: Impresszum
  - "A Gólyakörte 2022 weblapját az SSSL megbízásából a [Kir-Dev] (kir-dev.sch) [italics]:"speed-run munkasoport" készítette."
  - List all the contributors: "Fejlesztők"
    - Schámi, kir-dev profile picture, tags: [Project Leader, Backend]
    - etc...
  - "Felhasznált technológiák: Kotlin, Spring-boot, Typescript és React. Mint ahogy az összes többi projektünk ez is [nyílt forráskódú] (git url)! Ha kérdésed van vagy érdekel a többi projektünk is, látogass el az [oldalunkra] (kir-dev site) vagy keress fel minket a Kir-Dev standnál!"
  - "Az alaklamazás a KSZK Kubernetes clusterjében fut, köszönjük az erőforrást és a segítséget nekik ezúton is!"

### PR DESCRIPTION
**Pull request by DannySS123**
To avoid merge conflicts, the link in the footer will be added later in the footer update.
Closes #121

### CODE REVIEW

**Review by Tschonti — APPROVED** [review]

**Comment by Gerviba** [comment]
image

**Review by berenteb — COMMENTED** [review]
Looks awesome and fun! Have you been thinking about making the tags and borders orange? Just to match the font color you used! Anyway I approve everything, but I want to discuss this idea 😃

**Review by SepsiLaszlo — APPROVED** [review]

**Review by SepsiLaszlo — APPROVED** [review]

**Comment by berenteb** [comment]
Képernyőfotó 2022-01-26 - 16 31 32
How about grey borders with radius?

**Review by poiuztrewq1 — APPROVED** [review]
:100:

**Pull request merged**
