### PR TITLE
add multicolor progress circle

### PR DESCRIPTION
**Pull request by SepsiLaszlo**
## What is new?

- We implemented a multi color progress circle to indicate the submittted and and completed percents separately.
- Submitted percent is not displayed when zero

Screenshot from 2022-01-26 14-25-05

Screenshot from 2022-01-24 17-27-08

### CODE REVIEW

**Review by DannySS123 — APPROVED** [review]

**Review by berenteb — CHANGES_REQUESTED** [review]
It works great and looks nice, I have sharp eyes though:
Képernyőfotó 2022-01-26 - 18 10 25
Képernyőfotó 2022-01-26 - 18 11 13

- At 0% it should be white
- The linecap is weird 😃 
- Schámi said that in dark mode the white background of the circles are "raping" his eyes, so a gray.800 or smth would be better.
- OH LAWD HE A PIECHART

**Comment by Tschonti** [comment]
image

image
requested changes and design improvements

**Review by DannySS123 — APPROVED** [review]
🎨 🛠️

**Review by triszt4n — APPROVED** [review]
Cool and good 🍪 💯

**Comment by SepsiLaszlo** [comment]
@Tschonti, @DannySS123 thank you for implementing these features and doing the refactort! :rocket: 
These improvemnetes made the profile page a lot more user friendly. :bust_in_silhouette: :heart:

**Review by berenteb — APPROVED** [review]

**Pull request merged**
